### ISSUE TITLE
Overzicht debiteuren/crediteuren in backoffice

### ISSUE THREAD

**Issue by barthuttinga** [MyWheels/openwheels-support-frontend#29]
Zie ook ticket MW-1691 in Jira. Ik heb een start gemaakt in branch feature/MW-1691-debtors-creditors-list. Laat even weten als je vragen hebt.

**Comment by jorritdenbroeder** [comment]
Ik heb de state namen goedgezet (waarom had je die punt er eigenlijk weer tussengezet), dus je pagina's doen het. Wat is de volgende stap?

**Comment by barthuttinga** [comment]
Dank, deze kan dicht denk ik. Vervolg hierop staat in #34 en #35
