### ISSUE TITLE
Filter "unchecked" toevoegen bij accounts

### ISSUE THREAD

**Issue by barthuttinga** [MyWheels/openwheels-support-frontend#33]
/#/invoice2/accounts laat standaard alleen rekeningen zien die nog niet gecheckt zijn. Met param {unchecked:false} worden de rekeningen getoond die al wel gecheckt zijn. Daarvoor graag een filteroptie toevoegen. Filters die er nu staan (min/max) zijn geknipt/geplakt en mogen weg.

**Comment by jorritdenbroeder** [comment]
@bramtervoort @barthuttinga @Aronv90 De filter optie lijkt nog niet te werken, voor beide opties {unchecked: false} en {unchecked: true} komen dezelfde resultaten. Zie /invoice2/accounts
