### ISSUE TITLE
Factuur bewerken

### ISSUE THREAD

**Issue by barthuttinga** [MyWheels/openwheels-support-frontend#35]
Zolang een handgemaakte factuur (zie #34) nog niet gegroepeerd is (senderInvoiceGroup is null en recipientInvoiceGroup is null) mag deze nog bewerkt worden. Dit kan met `invoice2.alter(invoice, newProps)` waarbij newProps de params mag bevatten die bij `invoice2.create` opgegeven kunnen worden.

**Comment by jorritdenbroeder** [comment]
@barthuttinga @Aronv90 @bramtervoort Voor het editten van een invoice is een api-method "invoice2.get" nodig - ik meen dat Bart daarmee bezig was, klopt dat?

**Comment by barthuttinga** [comment]
@jorritdenbroeder ja klopt, is gedaan
